global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask_system'
    static_configs:
      - targets: ['192.168.80.2:5001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # CTF 메트릭 수집 (/metrics/ctf)
  - job_name: 'flask_ctf'
    static_configs:
      - targets: ['192.168.80.2:5001']
    metrics_path: '/metrics/ctf'
    scrape_interval: 15s